build: update ignores

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,26 +1,48 @@
 #!/bin/sh
 
+: printing utils
 fail() {
-	printf "\033[1m\033[31m[ FAIL ]\033[0m %s\n" "$1"
+	printf "\033[1m\033[31m[ %s ]\033[0m %s\n" "FAIL" "$*"
+}
+
+die() {
+	fail "$*"
 	exit 1
 }
 
 info() {
-	printf "\033[1m\033[36m[ INFO ]\033[0m %s\n" "$1"
+	printf "\033[1m\033[31m[ %s ]\033[0m %s\n" "INFO" "$*"
 }
 
-command -v pnpm >/dev/null 2>&1 || {
+: assert that the pnpm cmd exists
+pnpm_installed() {
+	if command -v pnpm >/dev/null 2>&1; then
+		return 0
+	else
+		return 1
+	fi
+}
+
+: assume that pnpm not being installed
+: is a result of nvm not being sourced
+pnpm_installed || {
 	NVM="${NVM_DIR:-"$HOME/.nvm"}/nvm.sh"
 
-	[ -f "$NVM" ] || fail "Please install \`pnpm\` globally!"
-
-	. "$NVM" || {
-		fail "Please install \`nvm\`!"
+	[ -f "$NVM" ] && {
+		. "$NVM" ||
+			die "Please install \`nvm\` and/or set \`NVM_DIR\` correctly!"
 	}
 }
 
+: ensure that pnpm was found
+pnpm_installed || {
+	die "\`pnpm\` has not been installed globally, please do so!"
+}
+
+: invoke husky git hook helper
 . "$(dirname "$0")/_/husky.sh"
 
+: begin repository checks
 info "Running \`fmt\` check..."
 pnpm run fmt:ci >/dev/null
 
